hijasdelacaridad/urls.py
try:
    from django.conf.urls import *
except:
    from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from ajax_select import urls as ajax_select_urls
from dajaxice.core import dajaxice_autodiscover, dajaxice_config


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    
    (r'^admin/jsi18n', 'django.views.i18n.javascript_catalog'),
    url(r'^search_form',  view='asientos_contables.views.search_form', name='search_form'),
    (r'^admin/lookups/', include(ajax_select_urls)),
    (r'^admin/', include(admin.site.urls)),
    (dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    #BANCOS
    (r'^cuentas_bancarias/(?P<id_comunidad>\d+)/(?P<id_banco>\d*)$', 'cuentas_bancarias.views.cuentas_bancarias'),
    (r'^cuentas_bancarias/comunidad/$', 'cuentas_bancarias.views.sel_comunidad_cuenta_bancaria'),    
    #REPORTES
    (r'^set_ejercicio/$', 'ejercicios.views.set_ejercicio'),
    (r'^reporte/$', 'asientos_contables.reports.some_view'),
    (r'^reporte_cuentas_bancarias_comunidad/(?P<id_comunidad>\d+)/$', 'asientos_contables.reports.cuentas_bancarias_comunidad'),
    (r'^reporte_inventario_general/$', 'asientos_contables.reports.inventario_general'),
    (r'^reporte_inventario/(?P<id_comunidad>\d+)/$', 'asientos_contables.reports.inventario_comunidad'),
    (r'^reporte_mayor/(?P<id_comunidad>\d+)/(?P<desde>[\w\-.]+)/(?P<hasta>[\w\-.]+)/$', 'asientos_contables.reports.mayor'),
    (r'^reporte_mayor_detalle/(?P<id_comunidad>\d+)/(?P<desde>[\w\-.]+)/(?P<hasta>[\w\-.]+)/$', 'asientos_contables.reports.mayor_detalle'),
    (r'^reporte/comunidad/(?P<id_comunidad>\d+)/$', 'asientos_contables.views.sel_comunidad_reporte_mayor'),
    (r'^reporte/comunidad/(?P<id_comunidad>\d+)/(?P<tipo>.*)$', 'asientos_contables.views.sel_comunidad_reporte_mayor'),
    
    #INVENTARIOS
    (r'^inventario/general/$', 'inventario.views.inventario_general'),
    (r'^inventario/comunidad/$', 'inventario.views.seleccionar_comunidad'),
    (r'^inventario/categoria/(?P<id_comunidad>\d*)$', 'inventario.views.inventario_comunidad'),
    (r'^inventario/categoria/(?P<id_comunidad>\d+)/(?P<id>\d+)$', 'inventario.views.inventario_comunidad'),
    (r'^inventario/categoria_detalle/(?P<id_comunidad>\d+)/(?P<id_categoria>\d+)$', 'inventario.views.categoria_detalle'),
    (r'^inventario/categoria_detalle/(?P<id_comunidad>\d+)/(?P<id_categoria>\d+)/(?P<id>\d+)$', 'inventario.views.categoria_detalle'),
    (r'^inventario/movimiento/(?P<id_detalle>\d+)/(?P<id>\d+)$', 'inventario.views.movimiento'),
    (r'^inventario/movimiento/(?P<id_detalle>\d+)$', 'inventario.views.movimiento'),
    (r'^inventario/movimiento_list/(?P<id_detalle>\d+)$', 'inventario.views.movimiento_list'),
    #ASIENTOS
    (r'^asiento/comunidad/$', 'asientos_contables.views.sel_comunidad_asiento'),
    (r'^asiento/nuevo/$', 'asientos_contables.views.nuevo'),
    (r'^asiento/nuevo/(?P<id_comunidad>\d+)/$', 'asientos_contables.views.nuevo'),
    (r'^asiento/editar/(?P<id>\d+)/$', 'asientos_contables.views.editar'),
    (r'^asiento/listar/', 'asientos_contables.views.listar'),
    (r'^cuentas/mayor/', 'asientos_contables.views.mayores'),
    (r'^mayor/(?P<tipo>.*)', 'asientos_contables.views.mayor'),
    (r'^mayorgeneral/(?P<tipo>.*)', 'asientos_contables.views.mayor_general'),
    
    #PRESUPUESTOS
    (r'^presupuesto_comunidad/(?P<id>\d+)/(?P<tipo>\w+)', 'presupuestos.views.presupuesto_comunidad'),
    (r'^ver_presupuesto/', 'presupuestos.views.ver_presupuesto'),
    
    (r'^ejecucion_presupuestaria/(?P<tipo>.*)', 'presupuestos.views.ejecucion_presupuestaria'),
    (r'^ejecucion_presupuestaria_comunidad/(?P<tipo>.*)', 'presupuestos.views.ejecucion_presupuestaria_comunidad'),
    (r'^balance/comunidad/(?P<id>.*)', 'cuentas.views.balance_comunidad'),
    (r'^balance/consolidado/', 'cuentas.views.balance_general'),
    (r'^balance/pais/(?P<id>.*)', 'cuentas.views.balance_pais'),
    (r'^balance/', 'cuentas.views.ver_balance'),
    (r'^prueba/', 'cuentas.views.prueba'),
    (r'^mayor_detalle_comunidad/(?P<id>\d+)/(?P<tipo>.*)', 'asientos_contables.views.mayor_detallado_comunidad'),
    (r'^mayor_detalle_pais/(?P<id>\d+)/(?P<tipo>.*)', 'asientos_contables.views.mayor_detallado_pais'),
    (r'^mayor_detalle_consolidado/(?P<tipo>.*)', 'asientos_contables.views.mayor_detallado_consolidado'),
    (r'^ver_mayor_detalle/', 'asientos_contables.views.ver_mayor_detalle'),
    (r'^asignar_permiso/(?P<tipo>.*)', 'cuentas.views.asignar_permiso'),
    (r'^cerrar_ejercicio/', 'ejercicios.views.cerrar_ejercicio'),
    
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cuentas/models.py
from django.db import models
from treebeard.mp_tree import MP_Node

TIPOS_DE_CUENTA = (
    ('AC', 'Activo'),
    ('PA', 'Pasivo'),
    ('PN', 'Patrimonio Neto'),
    ('IN', 'Ingresos'),
    ('EG', 'Egresos'),
)

class Cuenta(MP_Node):
    cuenta = models.CharField(max_length=200)
    tipo = models.CharField(max_length=2, choices=TIPOS_DE_CUENTA)
    codigo = models.CharField(max_length=30)
    codigo_ordenado = models.BigIntegerField(editable=False)
    permiso_debe=models.BooleanField(default=False)
    permiso_haber = models.BooleanField(default=False)
    
    debe = 0
    haber = 0
    cargado = False
        
    node_order_by = ['cuenta']

    def __unicode__(self):
        return self.cuenta
    
    def saldo(self):
        return self.debe - self.haber
    
    
    def cuenta_depth(self):
        return "____"*(self.depth-1) + self.codigo + "  " + self.cuenta
    
    def have_child(self):
        if self.numchild == 0:
            return False
        else:
            return True
 
    def codigo_conversion(self):
        if self.codigo is not None:
            codigo_vector = self.codigo.split(".")
            codigo_cadena = ""
            for codigo_parte in codigo_vector:
                if len(codigo_parte) == 1:
                    codigo_parte += "0"
                    codigo_cadena += codigo_parte
                else:
                    codigo_cadena=codigo_cadena[0:len(codigo_cadena)-1]+codigo_parte+'0'
            while len(codigo_cadena) <= 12:
                codigo_cadena += "00"
            return int(codigo_cadena)
        else:
            return None

    def cargar_tipo(self):
        if self.codigo is not None:
            if self.codigo[0] == '1':
                return 'AC'
            if self.codigo[0] == '2':
                return 'PA'
            if self.codigo[0] == '3':
                return 'PN'
            if self.codigo[0] == '4':
                return 'IN'
            if self.codigo[0] == '5':
                return 'EG'
            return ''
        else:
            return ''

cuentas_bancarias/models.py
from django.db import models
from comunidades.models import Comunidad

class CuentaBancaria(models.Model):
    comunidad = models.ForeignKey(Comunidad)
    cuenta_bancaria = models.CharField(max_length=50)
    nro_de_cuenta = models.CharField(max_length=50)
    observacion = models.CharField(max_length=200)
    saldo = models.DecimalField(max_digits=22, decimal_places=2,blank=True)

    class Meta:
        verbose_name_plural = "Cuentas bancarias"

    def __unicode__(self):
        return self.cuenta_bancaria+' - '+self.nro_de_cuenta
# Create your models here.

inventario/models.py
from django.db import models
from django.views.generic.dates import timezone_today
from comunidades.models import Comunidad

TIPO_MOVIMIENTO=(('INI','STOCK INICIAL'),
              ('ENT','ENTRADA'),
              ('SAL','SALIDA')
              )

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    
    #
    def total(self,id_comunidad):
        detalles=CategoriaDetalle.objects.filter(categoria=self,comunidad_id=id_comunidad)
        total=0
        for detalle in detalles:
            total+=detalle.precio_total()
        return total
    
    def cantidad(self,id_comunidad):
        detalles=CategoriaDetalle.objects.filter(categoria=self,comunidad_id=id_comunidad)
        total=0
        for detalle in detalles:
            total+=detalle.cantidad
        return total
    
        
    
    def __unicode__(self):
        return self.nombre
class CategoriaDetalle(models.Model):
    descripcion = models.CharField(max_length=200)
    categoria=models.ForeignKey(Categoria)
    cantidad=models.IntegerField()
    precio_unitario=models.DecimalField(max_digits=22,default=0,decimal_places=2)
    comunidad=models.ForeignKey(Comunidad)
    
    def __unicode__(self):
        return self.descripcion
    
    def precio_total(self):
        return self.precio_unitario*self.cantidad
    
class CategoriaDetalleMovimiento(models.Model):
    movimiento = models.CharField(max_length=3, choices=TIPO_MOVIMIENTO)
    observacion = models.CharField(max_length=200,null=True)
    categoria_detalle=models.ForeignKey(CategoriaDetalle)
    cantidad=models.IntegerField()
    fecha=models.DateField(default=timezone_today())
    
    
    
    
    
    

presupuestos/models.py
from django.db import models
from comunidades.models import Comunidad
from ejercicios.models import Ejercicio
from cuentas.models import Cuenta

MESES = (
    ('1', 'Enero'),
    ('2', 'Febrero'),
    ('3', 'Marzo'),
    ('4', 'Abril'),
    ('5', 'Mayo'),
    ('6', 'Junio'),
    ('7', 'Julio'),
    ('8', 'Agosto'),
    ('9', 'Septiembre'),
    ('10', 'Octubre'),
    ('11', 'Noviembre'),
    ('12', 'Diciembre'),
)

class Presupuesto(models.Model):
    ejercicio = models.ForeignKey(Ejercicio)
    mes = models.SmallIntegerField(choices=MESES)
    comunidad=models.ForeignKey(Comunidad)
    cuenta = models.ForeignKey(Cuenta)
    monto = models.DecimalField(max_digits=22, default=0, decimal_places=2)

    
# Create your models here.

inventario/forms.py
from django.forms import ModelForm
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from inventario.models import CategoriaDetalleMovimiento, CategoriaDetalle
from django.contrib.admin import widgets
from mx.DateTime.DateTime import today
from django.conf.global_settings import TIME_ZONE, DECIMAL_SEPARATOR
from django.views.generic.dates import timezone_today
from hijasdelacaridad import settings
from datetimewidget.widgets import DateTimeWidget
from datetime import datetime, time
from bootstrap_toolkit.widgets import BootstrapDateInput
import datetime

class FechaForm(forms.Form):
    fecha = forms.DateField(widget=BootstrapDateInput(), initial=datetime.date.today)

class PrecioForm(ModelForm):
    class Meta:
        model= CategoriaDetalle
        fields=['precio_unitario']
    precio_unitario= forms.IntegerField(widget=forms.TextInput(attrs={'style': 'heigth: 50px','step':'0.01'}))
    
class MovimientoForm(ModelForm):
     class Meta:
        model = CategoriaDetalleMovimiento
        fields=['movimiento','observacion','cantidad']
     fecha=forms.DateField(widget=widgets.AdminDateWidget(attrs={'readonly':'readonly','value': str(timezone_today().strftime('%d/%m/%Y'))}))
     cantidad=forms.IntegerField(min_value=0,widget=forms.DateInput())
    
             
     def save(self, commit=True):
        instance = super(MovimientoForm, self).save(commit=False)
        return instance
    
class DetalleForm(ModelForm):
    class Meta:
        model=CategoriaDetalle
        fields=['descripcion','cantidad','precio_unitario','fecha']
    fecha=forms.DateField(widget=widgets.AdminDateWidget(attrs={'readonly':'readonly','value': str(timezone_today().strftime('%d/%m/%Y'))}))
    cantidad=forms.IntegerField(min_value=0)
    precio_unitario=forms.IntegerField(min_value=0)
    
    def save(self, commit=True):
        instance = super(DetalleForm, self).save(commit=False)
        return instance

class DetalleReadOnlyForm(ModelForm):
    class Meta:
        model=CategoriaDetalle
        fields=['descripcion','cantidad','precio_unitario','fecha']
    fecha=forms.DateField(widget=widgets.AdminDateWidget(attrs={'readonly':'readonly','value': str(timezone_today().strftime('%d/%m/%Y'))}))
    cantidad=forms.IntegerField(min_value=0,widget=forms.TextInput(attrs={'readonly':'readonly'}))
    precio_unitario=forms.IntegerField(min_value=0)
    
    def save(self, commit=True):
        instance = super(DetalleReadOnlyForm, self).save(commit=False)
        return instance

              

cuentas_bancarias/views.py
from django.shortcuts import render
from cuentas_bancarias.models import CuentaBancaria
from comunidades.models import Comunidad
from django.shortcuts import render_to_response
from django.template import RequestContext
from asientos_contables.models import AsientoContableDetalle
from hijasdelacaridad.globales import USUARIO_LIMITADO, get_comunidad
from django.http.response import HttpResponseRedirect

# Create your views here.
def cuentas_bancarias(request,id_comunidad,id_banco=''):
    print request.user.has_perm(USUARIO_LIMITADO)

    if request.user.has_perm(USUARIO_LIMITADO):
        if get_comunidad(request.user) != int(id_comunidad):
            return HttpResponseRedirect('/admin')
    bancos=CuentaBancaria.objects.filter(comunidad_id=id_comunidad)
    if id_banco == '':
         if len(bancos) > 0:
            actual=bancos[0]
         else:
            actual=CuentaBancaria(pk=0)
    else:
        actual=CuentaBancaria.objects.get(pk=id_banco)
    if actual.id == 0:
        asientos_contables=[]
    else: 
        asientos_contables=AsientoContableDetalle.objects.filter(asiento_contable__comunidad_id=id_comunidad,cuenta_bancaria_id=actual.id)
    if id_banco != '':
        actual=CuentaBancaria.objects.get(pk=id_banco)
    
    comunidad=Comunidad.objects.get(pk=id_comunidad)
    
    return render_to_response('balance/cuentas_bancarias.html', {'comunidad': comunidad,'bancos':bancos,
                        'actual':actual,'asientos_contables':asientos_contables},
                              context_instance=RequestContext(request))

def sel_comunidad_cuenta_bancaria(request):
    app_label='Cuentas Bancarias'
    url="/asiento/listar/"
    if request.method == 'POST':
        id_comunidad=request.POST.get('comunidad_set-0-comunidad','')
        return HttpResponseRedirect('/cuentas_bancarias/'+str(id_comunidad))
    return render_to_response('balance/sel_comunidad.html',{'app_label':app_label,'url':url},
                                  context_instance=RequestContext(request))

    
    

    

templates/balance/categoria_detalle.html
<html xmlns="http://www.w3.org/1999/xhtml" lang="Es-es">
{% load my_tags %}
<head>
    <title>Descripcion</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    

    <!-- Le styles, placed after extrastyle to correctly override default styling -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/static/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    

    <!-- <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" /> -->
    <script type="text/javascript">
    //<![CDATA[
        window.__admin_media_prefix__ = "/static/admin/";
    //]]>
    </script>
    <script src="/static/admin/js/jquery-1.9.1.min.js"></script>
    <script src="/static/admin/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    
    {% load static %}


<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/widgets.css' %}"/>


<script type="text/javascript" 
    src="/admin/jsi18n/"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/jquery.js' %}"></script>

<script type="text/javascript" 
    src="{% static 'admin/js/actions.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/calendar.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>

    

    <meta name="robots" content="NONE,NOARCHIVE">
    <script type="text/javascript">
    //<![CDATA[
            (function($) {
                $(document).ready(function() {
                    $('input[type="submit"]').addClass('btn');
                    $('[title]').tooltip();
                });
            }(jQuery));
    //]]>
    </script>
   
    
</head>


<body  onload="DateTimeShortcuts.handleCalendarQuickLink(0, 0)">


<!-- Container -->
<div class="container-fluid">

    
    <!-- Header -->
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                
<a class="brand" href="/admin/">Hijas de la Caridad</a>

                <div class="nav-collapse collapse pull-right">
                    <ul class="nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bienvenido/a, <strong>{{ request.user.username }} </strong> <b class="caret"></b></a>
                            <ul class="dropdown-menu pull-right">
                                
                                <li><a href="/admin/password_change/">Cambiar contraseña</a></li>
                                
                                <li><a href="/admin/logout/">Terminar sesión</a></li>
                            </ul>
                        </li>
                            <li>
                        <a href="#" class="dropdown-toggle"><strong>Comunidad: {{ request.user.usuario.comunidad.comunidad }}</strong></a>
                    </li>
                        
                              
                        
                        
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <!-- END Header -->
    <div class="row-fluid">
        <div class="span12">
  <ul class="breadcrumb">
<li><a href="/admin/">Inicio</a> <span class="divider">/</span></li>
<li><a href="{% url 'inventario.views.inventario_comunidad' id_comunidad%}">Inventario</a> <span class="divider">/</span></li>
<li><a href="{% url 'inventario.views.inventario_comunidad' id_comunidad categoria.id %}">{{ categoria.nombre }}</a> <span class="divider">/</span></li>
<li>{{ modo }}</li>
</ul>
  	   
        </div>
    </div>
    

    <!-- Content -->
    <div id="content" class="colM">
        
        <div class="row-fluid">
            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand">Registrar Movimiento</a>
                </div>
            </div>
        </div>
        


<form method="post">{% csrf_token %}
<center>
<table class="table table-striped table-bordered" style="width: 400px">
<tbody>
	<tr>
		<th><label for="id_descripcion">Descripcion:</label></th>
		<td><input id="id_descripcion" maxlength="200" style="height: 30px" required  name="descripcion" value="{{ categoria_detalle.descripcion }}" type="text"></td>
	</tr>
	<tr>
		<th><label for="id_cantidad">Cantidad:</label></th>
		<td><input id="id_cantidad" min="0" name="cantidad" style="height: 30px" required {% if categoria_detalle.cantidad != None  %} readonly {% endif %} value="{{ categoria_detalle.cantidad }}" type="number"></td>
	</tr>
	<tr>
		<th><label for="id_precio_unitario">Precio unitario:</label></th>
		<td>
		<input id="id_precio_unitario" min="0"  name="precio_unitario" step="0.01" style="height: 30px"  required="required" value="{{ categoria_detalle.precio_unitario }}"  type="number">
		
		
		</td>
	</tr>
		<tr>
		<th><label for="id_fecha">Fecha:</label></th>
		<td><input class="vDateField" id="id_fecha" name="fecha" style="height: 30px" readonly="readonly" required type="text" value="{{ categoria_detalle.fecha }}">
		</td></tr>
</tbody></table>

<input type="submit" value="Grabar" class="btn-primary">
</center>

  </form>
         
    </div>
    <!-- END Content -->

    <footer id="footer"></footer>
</div>
<!-- END Container -->



</body></html>

templates/balance/cuentas_bancarias.html
{% extends 'admin/base_site.html' %}

{% load url from future %}
{% load my_tags %}
{% block title %} Inventario {% endblock %}
{% block extrahead %}

        
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<!-- Placed at the end of the document so the pages load faster -->
<script src="bootstrap-3.2.0-dist/js/bootstrap.min.js"></script>

{% endblock %}
{% block navbar %}
        <div class="row-fluid">
            <div class="navbar">
                <div class="navbar-inner">
                <table>
                <tr>
                <td style="width: 88%">
                    <a class="brand">Cuentas Bancarias: {{ comunidad.comunidad }}</a>
                    </td>
                    <td>
                    <a href="{% url 'asientos_contables.reports.cuentas_bancarias_comunidad' comunidad.id %}" class='btn btn-primary'>Descargar Reporte</a>
                    </td>
                   </tr>
                    </table>
                </div>
            </div>
        </div>
        {% endblock navbar %}
          {% block breadcrumbs %}
<ul class="breadcrumb">
<li><a href="/admin/">Inicio</a> <span class="divider">/</span></li>
	<li>Cuentas Bancarias</li>

</ul>
            {% endblock %}
{% block content %}



    <ul class="nav nav-tabs" role="tablist">
    {% for banco in bancos %}
  <li {% if actual.id == 0 and forloop.counter0 == 0  or actual.id == banco.id%} class="active" {% endif %}>
  <a href="{% url 'cuentas_bancarias.views.cuentas_bancarias' comunidad.id banco.id %}">{{ banco.cuenta_bancaria }}</a></li>
  {% endfor %}
</ul>
<table>
<td style="width: 86%"><td>
<td></td>

</table>
<br>
<center>
<table class="table table-striped table-bordered" style="width: 80%" >
<thead>
<th>Fecha</th><th>Debe</th><th>Haber</th><th>Saldo</th><th>Observaci&oacute;n</th>
{% for asiento in asientos_contables %}
<tr>
<td>{{ asiento.fecha }}</td>
<td>{{ asiento.debe }}</td>
<td>{{ asiento.haber }}</td>
<td>{% if forloop.counter0 == 0 %} {{ asiento.debe|sub:asiento.haber }} {% else %} {{ asientos_contables|saldo_anterior:forloop.counter0 }} {% endif %}</td>
<td>{{ asiento.observacion }}</td>
</tr>
{% endfor %}
</thead>
<tbody>
</tbody>

</table>

</center>
   
{% endblock %}

templates/balance/mayor_general.html
{% extends 'admin/base_site.html' %}
{% load bootstrap_toolkit %}
{% load url from future %}
{% load my_tags %}
{% block extrahead %}
        {% bootstrap_stylesheet_tag %}
    {% bootstrap_stylesheet_tag "responsive" %}
    {% bootstrap_javascript_tag %}
<!-- Placed at the end of the document so the pages load faster -->
<script src="bootstrap-3.2.0-dist/js/bootstrap.min.js"></script>

{% endblock %}
  {% block breadcrumbs %}
<ul class="breadcrumb">
	<li><a href="/admin/">Inicio</a> <span class="divider">/</span></li>
<li>Mayor Consolidado</li>
</ul>
  {% endblock %}
{% block navbar %}
        <div class="row-fluid">
            <div class="navbar">
                <div class="navbar-inner">
               
                <td style="width: 88%"><a class="brand">Mayor Consolidado</a></td>
                </div>
            </div>
        </div>
        {% endblock navbar %}
{% block content %}

    <center>
    <ul class="nav nav-tabs" role="tablist">
  <li {% if tipo == 'AC' %} class="active" {% endif %}><a href="{% url 'asientos_contables.views.mayor_general' 'AC' %}">Activo</a></li>
  <li {% if tipo == 'PA' %} class="active" {% endif %}><a href="{% url 'asientos_contables.views.mayor_general' 'PA' %}">Pasivo</a></li>
   <li {% if tipo == 'IN' %} class="active" {% endif %}><a href="{% url 'asientos_contables.views.mayor_general' 'IN' %}">Ingresos</a></li>
        <li {% if tipo == 'EG' %} class="active" {% endif %}><a href="{% url 'asientos_contables.views.mayor_general' 'EG' %}">Egresos</a></li>
  <li {% if tipo == 'PN' %} class="active" {% endif %}><a href="{% url 'asientos_contables.views.mayor_general' 'PN' %}">Patrimonio Neto</a></li>
</ul>

    
    <table class="table-striped table-bordered table" style="width: 80%">
       <tr>
      	<th style="width: 500px; text-align: center" class="navbar-inner"><p style="font-size: 20px">Cuenta</p></th>
      	<th  class="navbar-inner"><p style="font-size: 20px">Tipo</p></th>
      	<th  class="navbar-inner"><p style="font-size: 20px">Debe</p></th>
      	<th  class="navbar-inner"><p style="font-size: 20px">Haber</p></th>
      	<th  class="navbar-inner"><p style="font-size: 20px">Saldo</p></th>
      </tr>
    {% for cuenta in vector_cuentas %}
        <tr><td style="width: 300px">
            <p style=" font-size: 15px">
               {% if cuenta.have_child  %}
               <b>{{cuenta.codigo}} -  {{ cuenta.cuenta }}</b>
               {% else %}
                {{ cuenta.codigo }} - {{ cuenta.cuenta }}
                {% endif %}
            </p>
            </td>
            <td style="width: 150px"><p style="font-size: 15px">{{ cuenta.get_tipo_display }}</p></td>
            <td style="width: 100px"><p style="font-size: 15px; text-align: right">{{ cuenta.debe|separar }}</p></td>
            <td style="width: 100px"><p style="font-size: 15px; text-align: right">{{ cuenta.haber|separar }}</p></td>
            <td style="width: 100px"><p style="font-size: 15px; text-align: right">{{ cuenta.saldo|separar }}</p></td>
        </tr>
    {% endfor %}
    </table>

    </center>
{% endblock %}
<style>
.p{
    font-size: 15px;
}
</style>